set -U fish_color_command green
set -U fish_color_comment yellow
set -U fish_color_error red
set -U fish_color_param normal
set -U fish_color_quote yellow
set -U fish_color_redirection normal
set -U fish_color_autosuggestion brblack
set -U fish_color_operator blue
set -U fish_pager_color_description yellow
