set-option global startup_info_version 20211107
set-option global ui_options terminal_assistant=none
set-option global grepcmd 'rg --column --smart-case'
set-option -add global ctagsfiles '.git/tags'

map global insert <c-[> <esc>
map global insert <c-w> <esc>bdi
map global insert <c-b> <left>
map global insert <c-f> <right>
map global insert <c-a> <home>
map global insert <c-e> <end>

map global user w ': write<ret>' -docstring 'Write'
map global user b ':buffer ' -docstring 'Buffer'
map global user l ': enter-user-mode lsp<ret>' -docstring 'LSP'
map global user f ':find ' -docstring 'Find file'
map global user g ':git ' -docstring 'Git'
map global user / ':grep ' -docstring 'Grep'
map global user * ':grep %val{selection}<ret>' -docstring 'Grep for selection'

add-highlighter global/show-whitespaces show-whitespaces -tab '>' -tabpad ' ' -spc ' ' -lf ' '
add-highlighter global/show-matching show-matching

define-command find -menu -params 1 -shell-script-candidates %{rg --files} %{edit %arg{1}}

face global MenuBackground white,black,default
face global MenuForeground white,black,default+r
face global MatchingChar white,bright-black,default+b
