#!/bin/sh

set -euf

tag=$(git describe)
version=$(echo "$tag" | sed 's/^v//')
os=$(uname | tr '[:upper:]' '[:lower:]')
machine=$(uname -m)
name=$(basename "$(pwd)")
dir="$name"-"$version"
mkdir -p "$dir"
git ls-files 'LICENSE*' 'COPYING*' | xargs -I{} cp {} "$dir"

if [ -f Makefile ]; then
	make prefix="$dir" install
elif [ -f meson.build ]; then
	meson build
	meson compile -C build
	meson install -C build --destdir "$dir"
elif [ -f CMakeLists.txt ]; then
	mkdir -p build
	cmake --build build --prefix "$dir"
elif [ -f poetry.lock ]; then
	rm -rf dist
	poetry build -n
	find dist -type f -print0 | xargs -0 -I{} mv {} "$dir"/
fi

tar czf "$name"-"$version"-"$os"-"$machine".tar.gz "$name"-"$version"
